name: Review

pr:
  branches:
    include:
      - main
      - hotfix/*
  paths:
    include:
      - "*"
    exclude:
      - "docs/*"

stages:
  - stage: Review
    displayName: Review
    dependsOn: []

    jobs:
      - job: SmokeTest
        displayName: Smoke Test PR
        strategy:
          matrix:
            ubuntu:
              image: "ubuntu-latest"
        pool:
          vmImage: $(image)

        steps:
          - task: CmdLine@2
            displayName: Run npm install
            inputs:
              script: "npm install"

          - template: templates/smoke-test-template.yml
            parameters:
              version: review
